### ISSUE TITLE
Use another user group instead of root

### ISSUE THREAD

**Issue by MonFig** [vladshcherbin/rollup-plugin-copy#25]
I found out that the copied file was created by `root` instead of my current user group, and that causes I can not delete the file with out `sudo`.

code: 
```
        copy({
            targets: [{src: 'build/static/god/template.html', dest: 'build/test', rename: 'index.html'}],
        })
```
and when I want to remove the files I got: 
```
Failed to compile.

EACCES: permission denied, unlink '/Users/monkeyfigaro/workspace/sohu-inc/awesome-sohu/build/test/index.html'


error Command failed with exit code 1.
```
See the user groups:

![image](https://user-images.githubusercontent.com/16597492/64094890-c45da680-cd8f-11e9-9e06-18e52f29da9b.png)

**Comment by vladshcherbin** [comment]
@MonFig hey, this looks strange.

I've tried it in a a fresh test project and it gives me my user group.

![image](https://user-images.githubusercontent.com/6711845/64112861-4bf7e500-cd91-11e9-8d8e-1e43784fc8bd.png)

I've also tried to set `template.html` file group to `root` and copy after, but it also changed group to my current user one.

What's your OS, maybe you can link me your test repo since I don't know how to recreate this error in mine?

**Comment by vladshcherbin** [comment]
Maybe you can also try bare [copy function](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md) from [fs-extra](https://github.com/jprichardson/node-fs-extra) package.

It's used inside this package to copy stuff and I believe actual issue is there. It would be great to test if it copies with the same result. If yes, it will confirm that issue is in this function and we can open an issue in `fs-extra` package.

**Comment by MonFig** [comment]
It's strange that I can not recreate this issue either, which could be steadily repeated a few hours ago.  I would close this issue until I find out how to repeat it.

**Comment by lazarljubenovic** [comment]
You might've installed `npm` with `sudo`, and now running `npm run script-that-uses-rollup` is ran under root? Just a thought.
